### ISSUE TITLE
Import Excel Not Working

### ISSUE THREAD

**Issue by TaylorSorensen39** [Hoogkamer/vue-org-chart#86]
I exported the excel sheet in the edit mode, and then made a few changes, and then when back and clicked on import excel and nothing happens? 

Is there a step I'm missing to get it to work?

Thanks

**Comment by Hoogkamer** [comment]
Did you find it out already? Maybe you have an issue with the excel sheet and you get an error (press F12 to see the console log in your browser)

**Comment by y0d4a** [comment]
same here, got error in console:

```
a865292.js:2 TypeError: Cannot read properties of undefined (reading 'parent')
    at m.setShowDepartment (1b3c704.js:1:14515)
    at a865292.js:2:102546
    at a865292.js:2:104079
    at Array.forEach (<anonymous>)
    at a865292.js:2:104058
    at m._withCommit (a865292.js:2:105976)
    at m.commit (a865292.js:2:104032)
    at commit (a865292.js:2:99978)
    at m.setShowDepartment (1b3c704.js:1:8417)
    at Array.<anonymous> (a865292.js:2:102736)
He @ a865292.js:2
```

**Comment by y0d4a** [comment]
Hm, now i do not have those errors, but still imports do not work.. :/

**Comment by y0d4a** [comment]
I got the same issue, I only add new people with name, email, and position and when I do import, nothing happens...

**Comment by Hoogkamer** [comment]
@y0d4a @TaylorSorensen39 The issue should be fixed now. Can you please check?

**Comment by y0d4a** [comment]
Hi Hoogkamer, thank you for your response.
Sorry, but how to download the latest/fixed ver.? I see in the release that the latest is from 2 years ago.

I try to edit index.html and change the line which start with "<meta data-n-head="", but did not fix the issue (maybe that is not the right way to fix it?)

**Comment by Hoogkamer** [comment]
@y0d4a 
The most simple way is to download the zipfile via the website at the bottom: https://freeorgchart.netlify.app/

**Comment by y0d4a** [comment]
ah, sorry, now is fine! 
thank you for fix!
